export const FETCH_DATA_DEPARTMENT = "FETCH_DATA_DEPARTMENT";
export const SET_DATA_DEPARTMENT = "SET_DATA_DEPARTMENT";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const SHOW_DETAIL_DEPARTMENT = "SHOW_DETAIL_DEPARTMENT";
