export const FETCH_ALL_LEVEL = "FETCH_ALL_LEVEL";
export const FETCH_ADD_LEVEL = "FETCH_ADD_LEVEL";
export const FETCH_UPDATE_LEVEL = "FETCH_UPDATE_LEVEL";
export const DELETE_LEVEL = "DELETE_LEVEL";
