export const FETCH_ALL_SPECIALIZE = "FETCH_ALL_SPECIALIZE";
export const FETCH_ADD_SPECIALIZE = "FETCH_ADD_SPECIALIZE";
export const FETCH_UPDATE_SPECIALIZE = "FETCH_UPDATE_SPECIALIZE";
export const DELETE_SPECIALIZE = "DELETE_SPECIALIZE";
