export const FETCH_ALL_STAFF_TYPE = "FETCH_ALL_STAFF_TYPE";
export const FETCH_UPDATE_STAFF_TYPE = "FETCH_UPDATE_STAFF_TYPE";
export const FETCH_ADD_STAFF_TYPE = "FETCH_ADD_STAFF_TYPE";
export const DELETE_STAFF_TYPE = "DELETE_STAFF_TYPE";
